export const mainDrawerItems = [
  {
    label: "Exclusive",
    icon: "/imagew/imagew01.png",
    subItems: [{ img: "/imagew/exclusive-super-ace.jpg", itemName: "" }],
  },
  {
    label: "Sports",
    icon: "/imagew/imagew02.png",
    subItems: [
      { img: "/imagew/icon-exchange.svg", itemName: "Exchange" },
      { img: "/imagew/dreamLogo.svg", itemName: "Dream" },
      { img: "/imagew/icon-sportbook.svg", itemName: "Sports" },
      { img: "/imagew/icon-horsebook.svg", itemName: "Horsebook" },
    ],
  },
  {
    label: "Casino",
    icon: "/imagew/imagew03.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew10.png", itemName: "Evolution" },
      { img: "/imagew/imagew11.png", itemName: "Sexy" },
      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },
      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew14.png", itemName: "Microgaming" },
      { img: "/imagew/imagew15.png", itemName: "Hotroad" },
      { img: "/imagew/imagew16.png", itemName: "Dream gaming" },
    ],
  },
  {
    label: "Slots",
    icon: "/imagew/imagew04.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },
      { img: "/imagew/imagew19.png", itemName: "JDB" },
      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew21.png", itemName: "Fa chai" },
      { img: "/imagew/imagew33.png", itemName: "Spribe" },
      { img: "/imagew/imagew22.png", itemName: "Red tiger" },
      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew24.png", itemName: "Rich88" },
      { img: "/imagew/imagew25.png", itemName: "Worldmatch" },
      { img: "/imagew/imagew26.png", itemName: "CQ9" },
      { img: "/imagew/imagew27.png", itemName: "Joker" },
      { img: "/imagew/imagew28.png", itemName: "Play GO" },
      { img: "/imagew/imagew29.png", itemName: "Play 8" },
    ],
  },
  {
    label: "Table",
    icon: "/imagew/imagew05.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew27.png", itemName: "Joker" },
      { img: "/imagew/imagew28.png", itemName: "Play GO" },
      { img: "/imagew/imagew29.png", itemName: "Play 8" },
      { img: "/imagew/imagew19.png", itemName: "JDB" },
      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew21.png", itemName: "Fa chai" },
      { img: "/imagew/imagew33.png", itemName: "Spribe" },
      { img: "/imagew/imagew22.png", itemName: "Red tiger" },
      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },
      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew24.png", itemName: "Rich88" },
      { img: "/imagew/imagew25.png", itemName: "Worldmatch" },
      { img: "/imagew/imagew26.png", itemName: "CQ9" },
    ],
  },
  {
    label: "Crash",
    icon: "/imagew/imagew06.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew33.png", itemName: "Spribe" },

      { img: "/imagew/imagew27.png", itemName: "Joker" },

      { img: "/imagew/imagew19.png", itemName: "JDB" },
      { img: "/imagew/imagew25.png", itemName: "Worldmatch" },
      { img: "/imagew/imagew26.png", itemName: "CQ9" },

      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew21.png", itemName: "Fa chai" },

      { img: "/imagew/imagew22.png", itemName: "Red tiger" },
      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },
      { img: "/imagew/imagew28.png", itemName: "Play GO" },
      { img: "/imagew/imagew29.png", itemName: "Play 8" },
      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew24.png", itemName: "Rich88" },
    ],
  },
  {
    label: "Fishing",
    icon: "/imagew/imagew07.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew33.png", itemName: "Spribe" },
      { img: "/imagew/imagew27.png", itemName: "Joker" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew24.png", itemName: "Rich88" },
      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew19.png", itemName: "JDB" },
      { img: "/imagew/imagew25.png", itemName: "Worldmatch" },
      { img: "/imagew/imagew26.png", itemName: "CQ9" },
      { img: "/imagew/imagew28.png", itemName: "Play GO" },
      { img: "/imagew/imagew29.png", itemName: "Play 8" },
      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },
      { img: "/imagew/imagew21.png", itemName: "Fa chai" },
      { img: "/imagew/imagew22.png", itemName: "Red tiger" },
      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },
    ],
  },
  {
    label: "Arcade",
    icon: "/imagew/imagew08.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew33.png", itemName: "Spribe" },
      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew19.png", itemName: "JDB" },
      { img: "/imagew/imagew25.png", itemName: "Worldmatch" },
      { img: "/imagew/imagew26.png", itemName: "CQ9" },
      { img: "/imagew/imagew28.png", itemName: "Play GO" },
      { img: "/imagew/imagew29.png", itemName: "Play 8" },

      { img: "/imagew/imagew13.png", itemName: "Playtech" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },
      { img: "/imagew/imagew27.png", itemName: "Joker" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew24.png", itemName: "Rich88" },

      { img: "/imagew/imagew12.png", itemName: "Pragmetic play" },

      { img: "/imagew/imagew21.png", itemName: "Fa chai" },

      { img: "/imagew/imagew22.png", itemName: "Red tiger" },
    ],
  },
  {
    label: "Lottery",
    icon: "/imagew/imagew09.png",
    subItems: [
      { img: "/imagew/icon-all-provider.svg", itemName: "All" },
      { img: "/imagew/imagew17.png", itemName: "Jili" },
      { img: "/imagew/imagew23.png", itemName: "Yellow Bat" },
      { img: "/imagew/imagew27.png", itemName: "Joker" },
      { img: "/imagew/imagew18.png", itemName: "PG Soft" },

      { img: "/imagew/imagew33.png", itemName: "Spribe" },
      { img: "/imagew/imagew20.png", itemName: "Spadegaming" },
      { img: "/imagew/imagew19.png", itemName: "JDB" },
    ],
  },
];
